backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "docs/.vuepress/public/images"
public_folder: "images"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

